# Generated by Django 4.1 on 2024-07-25 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('name', 'state', 'district')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cr_id', models.CharField(default='', max_length=200)),
                ('name', models.CharField(default='', max_length=200)),
                ('email', models.CharField(default='', max_length=200)),
                ('phone', models.CharField(default='', max_length=200)),
                ('whatsapp', models.CharField(default='', max_length=200)),
                ('year', models.CharField(default='', max_length=200)),
                ('state', models.CharField(max_length=255)),
                ('district', models.CharField(blank=True, max_length=255, null=True)),
                ('points', models.IntegerField(default=0)),
                ('in_team', models.BooleanField(default=False)),
                ('ref', models.CharField(default='', max_length=200)),
                ('bonus_ref', models.CharField(default='', max_length=200)),
                ('is_individual', models.BooleanField(default=False)),
                ('tname', models.CharField(default='', max_length=200)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.college')),
            ],
        ),
    ]
