# Generated by Django 4.1 on 2024-07-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bonus_ref',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cr_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='in_team',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_individual',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='points',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='ref',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='tname',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='whatsapp',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='year',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='year_of_study',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='college',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
    ]
