# Generated by Django 4.2.14 on 2024-07-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_userprofile_bonus_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='representative_type',
            field=models.CharField(choices=[('college', 'College'), ('school', 'School')], default='college', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='school',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='college',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
