# Generated by Django 4.2.14 on 2024-07-25 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_collegerepresentative_schoolrepresentative'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='unique_id',
            field=models.CharField(default='DEFAULT_ID', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
