# Generated by Django 4.2.14 on 2024-07-25 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representative_type', models.CharField(max_length=50)),
                ('unique_id', models.CharField(max_length=50, unique=True)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
    ]
